### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sevenandseven** [sail-sg/sdft#1]
![image](https://github.com/sail-sg/sdft/assets/63324925/fa851fdb-8014-4efe-99a4-56b111622541)

Hello, I followed the instructions to download the LLamA-Factory and bigcode into a directory, and then run the sfdt.sh file under the alpha directory, but an error occurred. Could you please tell me what the problem is and how to solve it?
![屏幕截图 2024-03-19 090858](https://github.com/sail-sg/sdft/assets/63324925/617027e2-b595-4318-aafd-d7223882c4f0)

**Comment by rickyang1114** [comment]
Hi, thanks for your attention!

The module `train_bash` is actually from `LLaMA-Factory`, which is used as a submodule in the `main` branch. As vanilla `git
 clone` without the `--recurse-submodules` argument doesn't install submodules, you need to install the module manually. 

Here are the steps to do so:
1. Clone submodules:
```bash
git submodule update --init --recursive
```
2. Install the `LLaMA-Factory` module locally:
```bash
pip install -e LLaMA-Factory
```

Hope this helps.

**Comment by sevenandseven** [comment]
Thank you for your reply. Using your method, I was able to run the code.
