### ISSUE TITLE
现在已经有llama factory项目代码，怎么下载sdft，下载后对原来的llama factory的环境有影响吗

### ISSUE THREAD

**Issue by xiao-liya** [sail-sg/sdft#10]
我之前训练模型是用llama factory工具，现在想尝试一下sdft方法，我发现sdft代码中有llama factory，如果我直接下载sdft代码，会和之前的llama factory冲突吗，有没有推荐的安装方法

**Comment by SivilTaram** [comment]
@xiao-liya 你可以查看这个 commit，对应修改Llama-Factory的代码即可（就一行）

https://github.com/rickyang1114/LLaMA-Factory/commit/6ca8c1a00f6066e4bf46c0620b3ed4870435dff0

**Comment by xiao-liya** [comment]
> @xiao-liya 你可以查看这个 commit，对应修改Llama-Factory的代码即可（就一行）
> 
> [rickyang1114/LLaMA-Factory@6ca8c1a](https://github.com/rickyang1114/LLaMA-Factory/commit/6ca8c1a00f6066e4bf46c0620b3ed4870435dff0)

请问修改之后还是正常训练就行吧，我训练了一个，但是找不到重写的数据集在哪。

**Comment by xiao-liya** [comment]
> > @xiao-liya 你可以查看这个 commit，对应修改Llama-Factory的代码即可（就一行）
> > [rickyang1114/LLaMA-Factory@6ca8c1a](https://github.com/rickyang1114/LLaMA-Factory/commit/6ca8c1a00f6066e4bf46c0620b3ed4870435dff0)
> 
> 请问修改之后还是正常训练就行吧，我训练了一个，但是找不到重写的数据集在哪。

还有您能分享一下训练参数吗，我用之前的训练参数，不能实现sdft训练

**Comment by rickyang1114** [comment]
请仔细查看README的Usage部分。以下对相关内容进行摘抄：

To evaluate the seed language model, execute the following command: `bash scripts/test_seed_LM.sh`

For vanilla fine-tuning on a specific task dataset, use: `bash scripts/[dataset]/sft.sh`

For instance, to fine-tune on the Alpaca dataset, the command is: `bash scripts/alpaca/sft.sh`

Similarly, to perform Self-Distillation Fine (SDFT), the corresponding command is: `bash scripts/[dataset]/sdft.sh`

主要的超参数均可在对应的script中找到，未指定的超参数为LLaMA-Factory的默认值。
此外，使用sdft后，生成的数据集`[dataset]`的文件路径为`data/[dataset]/distilled_[dataset].json`，如[data/alpaca/distilled_alpaca.json](https://github.com/sail-sg/sdft/blob/main/data/alpaca/distilled_alpaca.json)。
