### ISSUE TITLE
Model Problem

### ISSUE THREAD

**Issue by MonrenZheng** [sail-sg/sdft#11]
I want to ask [Llama-2-7b-chat-hf](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf) or [Llama-2-7b-hf](https://huggingface.co/meta-llama/Llama-2-7b-hf) **which one** you use.
The link you gave jump to the [Llama-2-7b-hf](https://huggingface.co/meta-llama/Llama-2-7b-hf) but the the name in the readme is Llama-2-7b-chat-hf.

**Comment by rickyang1114** [comment]
We use [Llama-2-7b-chat-hf](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf). Sorry for the confusion and I will fix it soon.

**Comment by MonrenZheng** [comment]
> 我们使用 [Llama-2-7b-chat-hf](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf)。很抱歉造成混淆，我会尽快修复它。

Thanks for your reply
