### ISSUE TITLE
代码运行时间

### ISSUE THREAD

**Issue by SXxinxiaosong** [sail-sg/sdft#8]
![image](https://github.com/user-attachments/assets/07cb6460-e3fa-458f-9c83-cf758333c6fb)
您好，请问三条数据的训练速度就这么慢了吗？

**Comment by SivilTaram** [comment]
@SXxinxiaosong 感谢对我们工作的关注，可否请你确认一下机器的环境安装正确？看起来这么慢可能是因为没有GPU

**Comment by SXxinxiaosong** [comment]
#!/bin/bash
set -e
source "scripts/utils.sh"

# Configurations
model_path="/home/xsong/llama/llama-2-7b"
cuda_visible_devices="4"
type=sdft
train_dataset=gsm8k
output_folder="predictions/${train_dataset}/${type}"
result_file="results/${train_dataset}/${type}.log"
checkpoint_dir="checkpoints/${train_dataset}/${type}"
tmp_predictions_dir="predictions/${train_dataset}/${type}/distilled"

# Hyperparameters
epoch=5
lr=1e-4
per_device_train_batch_size=16

create_empty_file ${result_file}
echo -e "Fine-tuning using ${type}\n" >> ${result_file}

# Generate distilled dataset
CUDA_VISIBLE_DEVICES=${cuda_visible_devices} python main.py \
    --stage sft \
    --model_name_or_path ${model_path} \
    --do_predict \
    --dataset ${train_dataset}_train \
    --template gsm8k_distill \
    --output_dir ${tmp_predictions_dir} \
    --per_device_eval_batch_size 1 \
    --max_samples 9999999999999 \
    --predict_with_generate \
    --overwrite_cache \
    --fp16

python "eval/gen_distilled_data.py" \
    --dataset ${train_dataset} \
    --predict_jsonl ${tmp_predictions_dir}/generated_predictions.jsonl

# Train on distilled dataset
CUDA_VISIBLE_DEVICES=${cuda_visible_devices} python main.py \
    --stage sft \
    --model_name_or_path ${model_path} \
    --do_train \
    --dataset distilled_${train_dataset} \
    --template gsm8k \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --output_dir ${checkpoint_dir} \
    --overwrite_output_dir \
    --overwrite_cache \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate ${lr} \
    --num_train_epochs ${epoch} \
    --plot_loss \
    --bf16

# Evaluate math reasoning capabilities
for math_dataset in gsm8k multiarith;
do
    echo "Evaluation on ${math_dataset}:" >> ${result_file}
    output_dir="${output_folder}/${math_dataset}"
    CUDA_VISIBLE_DEVICES=${cuda_visible_devices} python main.py \
        --stage sft \
        --model_name_or_path ${model_path} \
        --adapter_name_or_path ${checkpoint_dir} \
        --do_predict \
        --dataset "${math_dataset}_test" \
        --template gsm8k_infer \
        --output_dir ${output_dir} \
        --per_device_eval_batch_size 1 \
        --max_samples 9999999999999 \
        --predict_with_generate \
        --overwrite_cache \
        --fp16

    python "eval/eval_math.py" --input_file "${output_dir}/generated_predictions.jsonl" >> ${result_file}
done

# Evaluate on OpenFunctions
echo "Evaluation on OpenFunctions:" >> ${result_file}
output_dir="${output_folder}/openfunction"
CUDA_VISIBLE_DEVICES=${cuda_visible_devices} python main.py \
    --stage sft \
    --model_name_or_path ${model_path} \
    --adapter_name_or_path ${checkpoint_dir} \
    --do_predict \
    --dataset openfunction_test \
    --template alpaca \
    --output_dir ${output_dir} \
    --per_device_eval_batch_size 1 \
    --max_samples 9999999999999 \
    --predict_with_generate \
    --overwrite_cache \
    --fp16

python "eval/eval_openfunction.py" --input_file "${output_dir}/generated_predictions.jsonl" >> ${result_file}

# Evaluate on HumanEval
output_path="${output_folder}/humaneval/result.json"
create_empty_file ${output_path}
CUDA_VISIBLE_DEVICES=${cuda_visible_devices} python bigcode-evaluation-harness/main.py \
    --model ${model_path} \
    --peft_model ${checkpoint_dir} \
    --tasks humanevalsynthesize-python \
    --prompt octocoder \
    --do_sample False \
    --batch_size 1 \
    --allow_code_execution \
    --trust_remote_code \
    --metric_output_path ${output_path} \
    --max_length_generation 2048 \
    --precision fp16

python "eval/eval_humaneval.py" --input_file ${output_path} >> ${result_file}

# Predict on alpaca_eval (general helpfulness)
output_dir="${output_folder}/alpaca_eval"
CUDA_VISIBLE_DEVICES=${cuda_visible_devices} python main.py \
    --stage sft \
    --model_name_or_path ${model_path} \
    --adapter_name_or_path ${checkpoint_dir} \
    --do_predict \
    --dataset alpaca_eval \
    --template alpaca \
    --output_dir ${output_dir} \
    --per_device_eval_batch_size 1 \
    --max_samples 9999999999999 \
    --predict_with_generate \
    --overwrite_cache \
    --fp16

python "eval/prepare_alpaca_eval.py" --input_file "${output_dir}/generated_predictions.jsonl" --output_file "${output_dir}/outputs.json"
# Execute the line below yourself if you want. Configuration of OpenAI API needed. The evaluation takes about $15.
# alpaca_eval --model_outputs "${output_dir}/outputs.json"

# Evaluate safety
for template in "alpaca" "alpaca_gcg";
do
    if [ ${template} == "alpaca" ];
    then
        safety_type="raw"
    else
        safety_type="jailbreak"
    fi
    echo "Evaluation on ${safety_type} safety:" >> ${result_file}
    output_dir="${output_folder}/advbench-${safety_type}"
    CUDA_VISIBLE_DEVICES=${cuda_visible_devices} python main.py \
        --stage sft \
        --model_name_or_path ${model_path} \
        --adapter_name_or_path ${checkpoint_dir} \
        --do_predict \
        --dataset advbench \
        --template ${template} \
        --output_dir ${output_dir} \
        --per_device_eval_batch_size 1 \
        --max_samples 9999999999999 \
        --predict_with_generate \
        --overwrite_cache \
        --fp16
    
    python "eval/keyword_eval_safety.py" --input_file "${output_dir}/generated_predictions.jsonl" >> ${result_file}
done

# Evaluate general knowledge 
output_dir="${output_folder}/lm-eval"
lm_eval --model hf \
    --model_args "pretrained=${model_path},peft=${checkpoint_dir}" \
    --tasks mmlu,truthfulqa,ai2_arc,hellaswag,winogrande \
    --device "cuda:${cuda_visible_devices}" \
    --batch_size 1 \
    --output_path ${output_dir}

python "eval/eval_general_knowledge.py" --input_file "${output_dir}/results.json" >> ${result_file}
echo "Evaluation after fine-tuning on ${train_dataset} using ${type} fininshed successfully. Results are saved in ${result_file}."

sh文件内容如上，为什么会没放到gpu上欸

**Comment by rickyang1114** [comment]
```bash
cuda_visible_devices="4"
```
这一行设置使用机器上的第5张显卡，如果机器上没有这么多显卡的话，是可能出问题的。不妨试试换成：
```bash
cuda_visible_devices="0"
```
再进行尝试。

**Comment by SXxinxiaosong** [comment]
我是用的8卡的A100，但是确实cuda:4上没放上任务，怎么会这样哇

**Comment by rickyang1114** [comment]
检查一下nvidia驱动？

**Comment by SXxinxiaosong** [comment]
通过nvidia-smi 吗？

**Comment by rickyang1114** [comment]
是的。也可以运行一下其他需要使用到显卡的程序，看是否运行正常。

**Comment by SXxinxiaosong** [comment]
显卡驱动是正常的
![image](https://github.com/user-attachments/assets/07884b04-eec2-416b-aa8e-c7988fad62b3)
但是通过提供的代码，没办法放到指定的卡上

**Comment by SXxinxiaosong** [comment]
似乎解决了谢谢！

**Comment by SXxinxiaosong** [comment]
还有一个问题是，如果我想在另外的数据集上进行训练，是不是只需要改变main.py中的template

**Comment by rickyang1114** [comment]
script中`--dataset` 参数指定数据集，该值对应`data/dataset_info.json`这个json文件中的key。

改变训练所用数据集所需的步骤如下：

1. 在`data/`目录中添加数据集文件。
2. 在`data/dataset_info.json`中进行配置。
3. 改script中的`--dataset` 参数为相对应的值。

至于template，这个视具体数据集的情况而定，并非一定要改。

**Comment by SXxinxiaosong** [comment]
训练集一万条左右，长度1024左右
   0%|          | 0/10924 [00:00<?, ?it/s]
  0%|          | 2/10924 [00:00<23:59,  7.59it/s]
  0%|          | 3/10924 [00:14<17:53:57,  5.90s/it]
  0%|          | 4/10924 [00:27<26:45:42,  8.82s/it]
  0%|          | 5/10924 [00:28<17:55:59,  5.91s/it]
  0%|          | 6/10924 [00:42<25:49:17,  8.51s/it]
  0%|          | 7/10924 [00:42<17:51:13,  5.89s/it]
  0%|          | 8/10924 [00:56<25:35:10,  8.44s/it]
  0%|          | 9/10924 [01:10<30:33:43, 10.08s/it]
  0%|          | 10/10924 [01:10<21:41:36,  7.16s/it]
  0%|          | 11/10924 [01:24<27:58:38,  9.23s/it]
 请问 这个速度和运行时间是正常的嘛

**Comment by rickyang1114** [comment]
感觉处于正常范围内。显存足够大可以试试增大`per_device_train_batch_size`，可能会更快。另外，对于A100可以试试安装flash-attn然后加上`--flash_attn` 参数以加快训练。

**Comment by SXxinxiaosong** [comment]
请问默认的配置是使用lora嘛

**Comment by rickyang1114** [comment]
是的，默认`finetuning_type lora`，也可以将其改为`full`。

**Comment by SXxinxiaosong** [comment]
1个epoch需要20多个小时吗？正常的lora只需要几十分钟

**Comment by SXxinxiaosong** [comment]
per_device_train_batch_size=4  
设置为4

[INFO|trainer.py:3834] 2024-08-07 20:48:24,714 >>   Batch size = 1  
日志输出是1

请问是什么问题呢

**Comment by rickyang1114** [comment]
我们的训练代码是基于 [LLaMA-Factory](https://github.com/rickyang1114/LLaMA-Factory/tree/1fa287fd637aad0c5e8893046515a54bbff4c009) 的，可以去那里的issue里面找找有没有相关的问题。

**Comment by SXxinxiaosong** [comment]
好哒！谢谢~
还有一个问题，我想做一个阅读理解的微调，可以使用哪一个template呢

**Comment by rickyang1114** [comment]
可以在alpaca模板的基础上修改，将`default_system`修改为特定阅读理解的指令：
```python
_register_template(
    name="alpaca",
    format_user=StringFormatter(slots=["### Instruction:\n{{content}}\n\n### Response:\n"]),
    format_separator=EmptyFormatter(slots=["\n\n"]),
    default_system=(
        "Below is an instruction that describes a task. " "Write a response that appropriately completes the request."
    ),
)
```

如果使用llama3-instruct，可以在其标准模板上修改：
```python
_register_template(
    name="llama3",
    format_user=StringFormatter(
        slots=[
            (
                "<|start_header_id|>user<|end_header_id|>\n\n{{content}}<|eot_id|>"
                "<|start_header_id|>assistant<|end_header_id|>\n\n"
            )
        ]
    ),
    format_system=StringFormatter(
        slots=[{"bos_token"}, "<|start_header_id|>system<|end_header_id|>\n\n{{content}}<|eot_id|>"]
    ),
    default_system="You are a helpful assistant.",
    stop_words=["<|eot_id|>"],
    replace_eos=True,
)
```

同理对llama-2-chat可以修改：
```python
_register_template(
    name="llama2",
    format_user=StringFormatter(slots=[{"bos_token"}, "[INST] {{content}} [/INST]"]),
    format_system=StringFormatter(slots=["<<SYS>>\n{{content}}\n<</SYS>>\n\n"]),
    default_system=(
        "You are a helpful, respectful and honest assistant. "
        "Always answer as helpfully as possible, while being safe. "
        "Your answers should not include any harmful, unethical, "
        "racist, sexist, toxic, dangerous, or illegal content. "
        "Please ensure that your responses are socially unbiased and positive in nature.\n\n"
        "If a question does not make any sense, or is not factually coherent, "
        "explain why instead of answering something not correct. "
        "If you don't know the answer to a question, please don't share false information."
    ),
)
```
